package my.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JFrame;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class Timetable_2 extends javax.swing.JPanel implements java.beans.Customizer {

    String input1;
    String input2;
    String input3;
    String input4;
    String input5;
    String input6;
    String input7;
    String input8;
    String input9;
    String input10;
    String input11;
    String input12;

    public static void main(String[] args) throws Exception {

        JFrame frame = new JFrame();
        frame.setSize(1000, 720);
        frame.add(new Timetable());
        frame.setVisible(true);
    }

    private Object bean;

    /**
     * Creates new customizer Test
     */
    public Timetable_2() {
        initComponents();
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea4 = new javax.swing.JTextArea();
        jTextArea5 = new javax.swing.JTextArea();
        jTextArea6 = new javax.swing.JTextArea();
        jTextArea7 = new javax.swing.JTextArea();
        jTextArea8 = new javax.swing.JTextArea();
        jTextArea9 = new javax.swing.JTextArea();
        jTextArea10 = new javax.swing.JTextArea();
        jTextArea11 = new javax.swing.JTextArea();
        jTextArea12 = new javax.swing.JTextArea();
        jTextArea13 = new javax.swing.JTextArea();
        jTextArea14 = new javax.swing.JTextArea();
        jTextArea15 = new javax.swing.JTextArea();
        jTextArea16 = new javax.swing.JTextArea();
        jTextArea17 = new javax.swing.JTextArea();
        jTextArea18 = new javax.swing.JTextArea();
        jTextArea19 = new javax.swing.JTextArea();
        jTextArea20 = new javax.swing.JTextArea();
        jTextArea21 = new javax.swing.JTextArea();
        jTextArea22 = new javax.swing.JTextArea();
        jTextArea23 = new javax.swing.JTextArea();
        jTextArea24 = new javax.swing.JTextArea();
        jTextArea25 = new javax.swing.JTextArea();
        jTextArea26 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("My Time Table");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Avaliable", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Input your course from course offer");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton3))))
                        .addGap(128, 128, 128))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Monday");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tuesday");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Wednesday");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Thursday");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Friday");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("08.30 - 10.30");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("10.30 - 12.30");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("12.30 - 14.30");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("14.30 - 16.30");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("16.30 - 18.30");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);

        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);

        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);

        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);

        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);

        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);

        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);

        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);

        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);

        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);

        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);

        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);

        jTextArea25.setColumns(20);
        jTextArea25.setRows(5);

        jTextArea26.setColumns(20);
        jTextArea26.setRows(5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea18, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jTextArea6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea16, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea21, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea19, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jTextArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea20, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextArea17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel1))
                                                        .addGap(520, 520, 520))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(67, 67, 67)
                                                        .addComponent(jLabel9)
                                                        .addGap(72, 72, 72)
                                                        .addComponent(jLabel10)
                                                        .addGap(59, 59, 59)))
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel11)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel12))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextArea23, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea22, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea24, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea25, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea26, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel11))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(41, 41, 41)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextArea7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextArea12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextArea17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextArea22, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea23, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea24, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea25, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextArea6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea21, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextArea26, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel1)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3)
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel4)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel5)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setLabel("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(68, 68, 68))
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel7))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] input = new String[12];

        input[0] = jTextField1.getText();
        input[1] = jTextField2.getText();
        input[2] = jTextField3.getText();
        input[3] = jTextField4.getText();
        input[4] = jTextField5.getText();
        input[5] = jTextField6.getText();
        input[6] = jTextField7.getText();
        input[7] = jTextField8.getText();
        input[8] = jTextField9.getText();
        input[9] = jTextField10.getText();
        input[10] = jTextField11.getText();
        input[11] = jTextField12.getText();

        int day1, day2;
        int pr1, pr2;

        try {
            Connection conn = DriverManager.getConnection("jdbc:ucanaccess://D:/User/Desktop/Project1.accdb");

            System.out.println("Connection Successful");

            Statement s = conn.createStatement();

            for (int i = 0; i < 11; i++) {
                String q = "SELECT * FROM Subject_Table WHERE Subject_ID = '" + input[i] + "'";
                ResultSet resultSet = s.executeQuery(q);

                if (resultSet != null) {
                    ResultSetMetaData resultSetMetaData = (ResultSetMetaData) resultSet.getMetaData();

                    if (input[i].length() > 0) {
                        resultSet.next();

                        day1 = resultSet.getInt("Subject_Day1");
                        day2 = resultSet.getInt("Subject_Day2");
                        pr1 = resultSet.getInt("Subject_Period1");
                        pr2 = resultSet.getInt("Subject_Period2");

                        if (day1 == 1 && pr1 == 1) {
                            jTextArea2.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr1 == 2) {
                            jTextArea7.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr1 == 3) {
                            jTextArea12.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr1 == 4) {
                            jTextArea17.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr1 == 5) {
                            jTextArea22.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr1 == 1) {
                            jTextArea3.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr1 == 2) {
                            jTextArea8.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr1 == 3) {
                            jTextArea13.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr1 == 4) {
                            jTextArea18.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr1 == 5) {
                            jTextArea23.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr1 == 1) {
                            jTextArea4.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr1 == 2) {
                            jTextArea9.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr1 == 3) {
                            jTextArea14.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr1 == 4) {
                            jTextArea19.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr1 == 5) {
                            jTextArea24.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr1 == 1) {
                            jTextArea5.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr1 == 2) {
                            jTextArea10.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr1 == 3) {
                            jTextArea15.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr1 == 4) {
                            jTextArea20.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr1 == 5) {
                            jTextArea25.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr1 == 1) {
                            jTextArea6.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr1 == 2) {
                            jTextArea11.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr1 == 3) {
                            jTextArea16.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr1 == 4) {
                            jTextArea21.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        }
                        if (day1 == 5 && pr1 == 5) {
                            jTextArea26.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr1 == 1) {
                            jTextArea2.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr1 == 2) {
                            jTextArea7.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr1 == 3) {
                            jTextArea12.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr1 == 4) {
                            jTextArea17.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr1 == 5) {
                            jTextArea22.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr1 == 1) {
                            jTextArea3.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr1 == 2) {
                            jTextArea8.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr1 == 3) {
                            jTextArea13.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr1 == 4) {
                            jTextArea18.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr1 == 5) {
                            jTextArea23.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr1 == 1) {
                            jTextArea4.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr1 == 2) {
                            jTextArea9.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr1 == 3) {
                            jTextArea14.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr1 == 4) {
                            jTextArea19.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr1 == 5) {
                            jTextArea24.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr1 == 1) {
                            jTextArea5.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr1 == 2) {
                            jTextArea10.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr1 == 3) {
                            jTextArea15.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr1 == 4) {
                            jTextArea20.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr1 == 5) {
                            jTextArea25.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr1 == 1) {
                            jTextArea6.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr1 == 2) {
                            jTextArea11.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr1 == 3) {
                            jTextArea16.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr1 == 4) {
                            jTextArea21.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr1 == 5) {
                            jTextArea26.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        }
                        if (day1 == 1 && pr2 == 1) {
                            jTextArea2.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr2 == 2) {
                            jTextArea7.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr2 == 3) {
                            jTextArea12.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr2 == 4) {
                            jTextArea17.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 1 && pr2 == 5) {
                            jTextArea22.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr2 == 1) {
                            jTextArea3.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr2 == 2) {
                            jTextArea8.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr2 == 3) {
                            jTextArea13.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr2 == 4) {
                            jTextArea18.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 2 && pr2 == 5) {
                            jTextArea23.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr2 == 1) {
                            jTextArea4.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr2 == 2) {
                            jTextArea9.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr2 == 3) {
                            jTextArea14.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr2 == 4) {
                            jTextArea19.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 3 && pr2 == 5) {
                            jTextArea24.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr2 == 1) {
                            jTextArea5.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr2 == 2) {
                            jTextArea10.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr2 == 3) {
                            jTextArea15.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr2 == 4) {
                            jTextArea20.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 4 && pr2 == 5) {
                            jTextArea25.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr2 == 1) {
                            jTextArea6.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr2 == 2) {
                            jTextArea11.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr2 == 3) {
                            jTextArea16.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day1 == 5 && pr2 == 4) {
                            jTextArea21.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        }
                        if (day1 == 5 && pr2 == 5) {
                            jTextArea26.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr2 == 1) {
                            jTextArea2.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr2 == 2) {
                            jTextArea7.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr2 == 3) {
                            jTextArea12.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr2 == 4) {
                            jTextArea17.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 1 && pr2 == 5) {
                            jTextArea22.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr2 == 1) {
                            jTextArea3.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr2 == 2) {
                            jTextArea8.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr2 == 3) {
                            jTextArea13.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr2 == 4) {
                            jTextArea18.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 2 && pr2 == 5) {
                            jTextArea23.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr2 == 1) {
                            jTextArea4.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr2 == 2) {
                            jTextArea9.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr2 == 3) {
                            jTextArea14.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr2 == 4) {
                            jTextArea19.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 3 && pr2 == 5) {
                            jTextArea24.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr2 == 1) {
                            jTextArea5.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr2 == 2) {
                            jTextArea10.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr2 == 3) {
                            jTextArea15.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr2 == 4) {
                            jTextArea20.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 4 && pr2 == 5) {
                            jTextArea25.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr2 == 1) {
                            jTextArea6.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr2 == 2) {
                            jTextArea11.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr2 == 3) {
                            jTextArea16.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr2 == 4) {
                            jTextArea21.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        } else if (day2 == 5 && pr2 == 5) {
                            jTextArea26.append(resultSet.getString("Subject_ID") + "  " + resultSet.getString("Instructor_Name") + "\n");
                        }
                    }
                }
            }

        } catch (Exception e) {
            System.out.println("Serious error has occured");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");

        jTextArea2.setText("");
        jTextArea3.setText("");
        jTextArea4.setText("");
        jTextArea5.setText("");
        jTextArea6.setText("");
        jTextArea7.setText("");
        jTextArea8.setText("");
        jTextArea9.setText("");
        jTextArea10.setText("");
        jTextArea11.setText("");
        jTextArea12.setText("");
        jTextArea13.setText("");
        jTextArea14.setText("");
        jTextArea15.setText("");
        jTextArea16.setText("");
        jTextArea17.setText("");
        jTextArea18.setText("");
        jTextArea19.setText("");
        jTextArea20.setText("");
        jTextArea21.setText("");
        jTextArea22.setText("");
        jTextArea23.setText("");
        jTextArea24.setText("");
        jTextArea25.setText("");
        jTextArea26.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
